markdown: kramdown
highlighter: Rouge
permalink: /:year/:month/:day/:title.html
name: "Takes time to be twisted, or not"
markdown: kramdown

author: "Yuanhang Liu"
disqus: "gopherwood"

navigations:
  - title: Archive
    class: fa fa-list-ul
    href: /archive.html
  - title: Tags
    class: fa fa-tags
    href: /tags.html
  - title: About
    class: fa fa-user
    href: /about.html
  - title: Gallery
    class: fa fa-film
    href: https://www.flickr.com/photos/133563883@N05/

